# guessing the secret number generated by the computer
# random.randint is telling comp to generate random number between start to stop
#the sys gives us idea about how near we are to the number
import random
def guess(x):
    random_no = random.randint(1,x)
    guess = 0
    while guess != random_no:
        guess = int(input(f'guess a number between 1 and {x}: '))
        if guess < random_no:
            print("too low guess again OOPS!!!")
        elif guess > random_no:
            print("OOPS your guess is too high  try again!")
    print(f"voila!!!! you guessed it right: {random_no}")
    




guess(20) #defining the value of x

